version: "2"
services:
  nginx:
    image: nginx
    container_name: nginx_webserver
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_error.log:/etc/nginx/error_log.log
      - /home/torage/cert/:/home/torage/cert/
      - /home/torage/Pathfinder/dist/:/var/www/html/
    ports:
      - 80:80
      - 443:443
      - 9090:9090
  db:
    image: mongo
    container_name: mongoserver
    restart: always
  app:
    image: mirkobrandt/pathfinder
    build: .
    restart: always
    ports:
    - 8080:8080
    depends_on:
    - db